pipeline {
  agent any
  stages {
    stage("Clean Up - Jenkins Pipeline2 Branch"){
        steps {
            deleteDir()
        }
    }   
    stage("Clone Repo - Jenkins Pipeline2 Branch") {
        steps {
            sh "git clone https://github.com/akiltipu/jenkins-aws-java-maven-app.git"
        }
    }
    stage("Build - Jenkins Pipeline2 Branch") {
        steps {
           dir("jenkins-aws-java-maven-app") {
              sh "mvn clean install"
           }
        }
    }
    stage("Test - Jenkins Pipeline2 Branch"){
        steps {
           dir("jenkins-aws-java-maven-app") {
              sh "mvn test"
           }
        }
    }
  }
}