pipeline {
  agent any
  stages {
    stage("Clean Up"){
        steps {
            deleteDir()
        }
    }   
    stage("Clone Repo") {
        steps {
            sh "git clone https://github.com/siba-x-prasad/jenkins-aws-java-maven-app-Swasi.git"
        }
    }
    stage("Build") {
        steps {
           dir("jenkins-aws-java-maven-app") {
              sh "mvn clean install"
           }
        }
    }
    stage("Test"){
        steps {
           dir("jenkins-aws-java-maven-app") {
              sh "mvn test after SCM POLL set 2 2 minutes"
           }
        }
    }
  }
}